### Get All categories
GET http://localhost:3000/api/categories
accept: application/json
Content-Type: application/json

### Get Specific categories 
GET http://localhost:3000/api/categories/
Accept: application/json
Content-Type: application/json


### Create new categories
POST http://localhost:3000/api/categories
Accept: application/json 
Content-Type: application/json

{
     "name":"binatang"
}

### Update categories
PUT http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
     "id":3,
     "name": "Hewan"
}

### Delete categories
DELETE http://localhost:3000/api/categories/3
Accept: application/json
Content-Type: application/json